services:
 
  app:
    build: .
    container_name:  dados_sentinela
    ports:
      - "3010:3002"
    volumes:
      - dados_sentinela:/app/backend/data
 
volumes:
 
   dados_sentinela:

